[workspace]
members = [
    "lib/p2p",
    "lib/core",
    # "app/desktop/ffi",
    "tools/udpm"
]

[workspace.dependencies]
tokio = "1.29.1"
tokio-util = "0.7.8"
tracing = "0.1.37"
thiserror = "1.0.38"
serde = "1.0.152"
futures = "0.3.28"
bytes = "1.4.0"
